version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: github_stars
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=github_stars
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/github_stars
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/app
    command: ["python", "crawl_pool.py", "--repos", "100000", "--batch-size", "10000", "--clean-db"]

volumes:
  postgres_data: